language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository

before_cache:
  - find $HOME/.gradle/caches -name "*.lock" -delete

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
   - ./gradlew clean build